version: '3'
services:
  web:
    image: zhuyili
    build: .
    volumes:
      - .:/app
    ports:
     - "3000:3000"
  mongodb:
    image: "mongo:4"
    volumes:
      - mongo_data:/data/db:rw

volumes:
  mongo_data:
    driver: local
